name: Eslint and TDD Tests
on: push
jobs:
  check_lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npm run lint
  run_tests:
    needs: check_lint
    runs-on: ubuntu-latest
    env:
      FIREBASE_CRED: ${{ secrets.FIREBASE_CRED }}
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run Tests with Jest
      run: npm run test